
/*------------------------------------------------------------------------
    File        : IDestroyable
    Purpose     : 
    Syntax      : 
    Description : 
    Author(s)   : bronc
    Created     : Fri Dec 20 13:46:09 CET 2019
    Notes       : 
  ----------------------------------------------------------------------*/

using Progress.Lang.*.

interface bfvlib.process.IDestroyable:  

    method public void Destroy().
    
end interface.