
/*------------------------------------------------------------------------
    File        : IExecutable
    Purpose     : 
    Syntax      : 
    Description : 
    Author(s)   : bronco
    Created     : Wed Aug 01 05:49:15 CEST 2018
    Notes       : 
  ----------------------------------------------------------------------*/


interface bfvlib.process.IExecutable:  
  
  method public void Execute().
    
end interface.