
/*------------------------------------------------------------------------
    File        : ISingleton
    Purpose     : 
    Syntax      : 
    Description : 
    Author(s)   : bronc
    Created     : Fri Dec 20 14:05:42 CET 2019
    Notes       : 
  ----------------------------------------------------------------------*/

using Progress.Lang.*.

interface bfvlib.process.ISingleton:  
  
end interface.