
/*------------------------------------------------------------------------
    File        : ISerializableDataStructure
    Purpose     : 
    Syntax      : 
    Description : 
    Author(s)   : bronco
    Created     : Sat Jul 21 08:26:07 CEST 2018
    Notes       : 
  ----------------------------------------------------------------------*/

using OpenEdge.Core.Collections.IMap.

interface bfvlib.serialize.ISerializableDataStructure:  
  
  method public IMap GetDataStructures().
  
end interface.
