 
 /*------------------------------------------------------------------------
    File        : Address
    Purpose     : 
    Syntax      : 
    Description : 
    Author(s)   : bronco
    Created     : Sat Jul 21 10:26:29 CEST 2018
    Notes       : 
  ----------------------------------------------------------------------*/

block-level on error undo, throw.

class bfvlib.serialize.test.Address serializable: 
  
  define public property Street as character no-undo get. set.
  define public property HouseNumber as integer no-undo get. set.
  define public property Municipale as character no-undo get. set.
  define public property Postcode as character no-undo get. set.
  
end class.