# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches:
      - master
        
#   pull_request:
#     branches: 
#       - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
     
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: devbfvio/oe-pub:builder-11.7

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # turn secret into /app/license/progress.cfg file
    - name: create progress.cfg
      run: |
        echo ${{ secrets.progresscfg }} > /app/license/progress.cfg.b64,
        base64 -d < /app/license/progress.cfg.b64 > /app/license/progress.cfg.
      
    # Runs a single command using the runners shell
    - name: try to run ant
      run: ant
